# Pebble tile configuration

memBallChannelNum = 6

[privateDCache]
enable = false
ways = 4
capacityKB = 256
writeBytes = 8
portFactor = 2
memCycles = 10

[sharedMem]
enable = false
entries = 16384
inputChannels = 7
defaultGroupCount = 1

[[cores]]
core_id = 0
include = "../../../../../cores/pebble/configs/default.toml"
