[workloads]
search_path = "workloads/src"
tests = [
  "toy-toy-ctest-mvin_mvout_test-rushB-verilator-run",
  "toy-toy-ctest-mvin_mvout_stride_test-rushB-verilator-run",
  "toy-toy-ctest-bdb_counter_test-rushB-verilator-run",
  "toy-toy-ctest-gemmini_os_risc_atranspose_test-rushB-verilator-run",
  "toy-toy-ctest-gemmini_os_risc_btranspose_test-rushB-verilator-run",
  "toy-toy-ctest-gemmini_os_risc_abtranspose_test-rushB-verilator-run",
  "toy-toy-ctest-gemmini_os_risc_shift_test-rushB-verilator-run",
  "toy-toy-ctest-gemmini_ws_risc_basic_test-rushB-verilator-run",
]
