# multi-rocket Tile (48 Rocket-only cores)

[privateDCache]
enable = true
ways = 4
capacityKB = 256
writeBytes = 8
portFactor = 2
memCycles = 10

[sharedMem]
enable = false
entries = 16384
inputChannels = 48
defaultGroupCount = 1
memCycles = 10

[coreTemplate]
core_ids = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
include = "../../../../../cores/rocket/configs/default.toml"
count = 48
